- lua/overseer/parser/debug.lua
If the user did not have an 'overseer' directory in their cache, the debug parser would fail to start.
Check if the user has an 'overseer' directory, and if not, create one before running the debug session.
> fix: debug parser no overseer dir error

- README.md
The link to the built-in actions (in `actions.lua`) was broken and led to an invalid page.
Fix the invalid link by removing the part that caused the problem.
> fix: link to actions.lua in the README

- lua/neotest/consumers/overseer.lua
To run test file, the example given in Neotest is :
`require("neotest").run.run(vim.fn.expand("%"))`
The `args` parameter is therefore a `string` and it is not compatible with Overseer consumer.
This PR fixes this issue.
> fix: add compatibility for neotest test file run

- lua/overseer/template/cargo.lua
Checks for existence of `Cargo.toml` in parent directories rather than just `opts.dir`. This allows the user to be editing any file in a Rust project and use `cargo` commands from Overseer. Fixes #24. Let me know if anything else needs to be changed!
> feat(cargo): change conditional callback function

- lua/overseer/template/builtin.lua
- lua/overseer/template/mix.lua
first off, thank you very much for this plugin, it really great! much appreciated!
i've written some integration for the elixir mix system. the contents of the elixir files is elixir code, so it's not possible to parse it from lua, the only way to list the tasks is to run `mix help`. The downside is that that takes a little bit of time to run the help, so that slows down the display a little, but there's no other way that i can think of.
> add elixir mix support

- doc/overseer.txt
- doc/reference.md
- lua/overseer/config.lua
- lua/overseer/task_list/bindings.lua
Currently there is no binding for opening the output in the quickfix window, you have to navigate to the actions menu and select the quickfix option. This will add a binding (default <C-q>) to open the quickfix window from the task list.
> feat: add quickfix keybind

- lua/overseer/form/init.lua
- lua/overseer/form/utils.lua
- lua/overseer/template/mix.lua
Per #71
This changes some of the formatting of the generated mix task parameters so that users will be prompted to input any args. This preserves the programmatic functionality of `run_template({name = "mix", params = {args = {'taskname', '--flag', '-o', 'option'}}})`
> fix: mix tasks should generally prompt user for args

- lua/overseer/strategy/toggleterm.lua
Implements the "ToggleTerm" strategy, which sources a terminal through ToggleTerm's `Terminal.new()` command. ToggleTerm will open up and run your task in it's own window, while preserving operation in the same way as the default terminal strategy (e.g. you can view output through the Overseer pane and status is correctly reported).
> Adds the 'toggleterm' strategy

- README.md
- doc/third_party.md
This adds documentation to the "third party" section of the README and docs, and refers to the existing `strategies.md` documentation.
> Added toggleterm to third_party.md and ref in README.md

- lua/overseer/window.lua
OverseerOpen will only focus the window if it wasn't opened previously, which seems not to match the documentation, which mentions to use the ! if the user doesn't want to focus.
This change makes OverseerOpen always focus the window, whether it was previously open or not (unless the ! is given).
> OverseerOpen: focus also existing window

- lua/overseer/template/npm.lua
- lua/overseer/template/vscode/provider/npm.lua
Detect `pnpm` via `pnpm-lock.yaml` similar to how we're doing for `yarn`. Changed the internal interface to expect an executable name instead of just a flip on `use_yarn`. That didn't look to me like an API that was exposed so it seemed safe to remove it.
> feat(npm): detect pnpm

- doc/third_party.md
- lua/overseer/strategy/toggleterm.lua
Hi!
Lovely plugin! Thanks for creating it.
I use overseer to run tasks while programming Python. In particular, I have it run `python -m pip instal .` with some extra commands. I also use pyright with pyrightconfig.json, where I set the virtual environment to use. I have written some Lua to have neovim automatically use that virtual environment in `neotest` and `nvim-dap` and automatically source the `activate` script on creating `toggleterm` terminals. I use the vscode.json integration.
It enables support for the `on_create` callback from `toggleterm` so that one can run commands in the terminal before the task is started (if `use_shell=true`). I use this to source my virtual environment. But I suspect it can be useful for others as well. 
None that I can see. But there might be an …
> Add support for on_create in toggleterm strategy

- lua/overseer/strategy/toggleterm.lua
Before running the `restart` action on a task with the toggleterm strategy would make a second window appear if one was already open. This change calls `term:close()` in the `reset` method of the toggleterm strategy, to fix this issue.
To have access to the terminal handler in the `reset` method, I had to save it in the object as `self.term`.
> fix: make toggleterm terminal window close when task resets

- lua/overseer/component/on_output_quickfix.lua
Value can be one of "always", "failure" or "never". If it is "failure", the quickfix only opens if the command exits with a non-zero exit code.
> feat: add open_on_exit param for on_output_quickfix component

- doc/third_party.md
- lua/overseer/strategy/toggleterm.lua
This option closes the terminal window (with `term:close()`) but does not get rid of the terminal buffer. This way you can still open in back up and view the output if necessary.
See #152
> feat: add quit_on_exit option for toggleterm strategy

- lua/overseer/template/cargo.lua
This adds `cargo doc --open` and `cargo fmt`
> feat: add additional commands to cargo

- lua/overseer/template/vscode/problem_matcher.lua
The filename match group should be a lazy/non-greedy any-character pattern, as per original cpp-tools source, to more accurately match the filename at the start of the line.
This fixes diagnostics parsing on Windows where paths sometimes have a drive letter and colon at the start of the filename
> fix: change the filename capture group to lazy/non-greedy match any char

- doc/overseer.txt
- lua/overseer/binding_util.lua
- lua/overseer/config.lua
Adds a few configuration options for the help float so that users can set its border, winhl etc. to match the rest of their theme.
> feat: allow configuration of help float

- lua/overseer/template/just.lua
According to https://github.com/casey/just#quick-start the name can be uppercase or start with a dot:
> The search for a justfile is case insensitive, so any case, like Justfile, JUSTFILE, or JuStFiLe, will work. just will also look for files with the name .justfile, in case you'd like to hide a justfile.
> fix: ignore case when searching for "justfile", support hidden files

- lua/overseer/init.lua
Fixes #212 
I removed the `enabled` parameter since this solution assumes that `enabled` is always true when invoking the function.
> fix: lazy-load dap when patching

- lua/overseer/template/cargo-make.lua
Small fix for #130. TOML accepts all characters as key.
> fix: cargo-make task search pattern

- lua/overseer/template/npm.lua
On monorepo, we may not want to execute npm scripts on current dir.
eg.
```
- repository root
- package 1
- package.json (with script like `build`)
- src
- some file.ts
- package 2
- package.json
- ...
```
Currently when we run task of npm template on `some file.ts`, script (like `npm run build`) executed on root dir. This might be wrong.
> feat: change cwd to buffer dir on npm template for nested packages

- doc/guides.md
- doc/overseer.txt
- doc/reference.md
- lua/overseer/init.lua
`name` seems to be required for `template_provider`.
closes #236
> doc: Add name field to template_provider documentation

- lua/overseer/template/mix.lua
so i didn't upgrade overseer in my config for a very long time... And I just now got the change where it's not anymore the current folder that's taken into account, but the current file's folder.
I needed that change to keep getting all the mix tasks that I would get previously...
> mix: invoke in the folder of the mix.exs

- lua/overseer/commands.lua
- lua/overseer/template/init.lua
- lua/overseer/template/vscode/init.lua
I added a field to the TemplateDefinition called `hide`, that is used in the `run_template` function to filter templates and only show to the user the not hidden one.
I tried reading the code base and it seemed the most concise yet aligned solution I could come up with.
Please let me know if there are any chore addition needed, it didn't seem the documentation should be updated since it is an "internal" change nothing new should be exposed to the user.
I hope you'd like it and maybe it can close issue #269
> Support for vscode's "hide" option

- lua/lualine/components/overseer.lua
The other status icons/glyphs have an additional space defined, without this space the running task count number gets squeezed with the icon (at least with my terminal set-up).
Note: This is probably a `grapheme cluster` thing (https://mitchellh.com/writing/grapheme-clusters-in-terminals)
--
BTW: thanks for creating and sharing `overseer`, it is IMHO a beautiful piece of engineering which inspires me a lot 🙏🏻
> fix: add missing space after `running` glyph

- doc/guides.md
The callback cannot be used as is, it follows the same logic as for templates.
> [fix] condition field in the provider documentation

- doc/components.md
- doc/overseer.txt
- doc/reference.md
- lua/overseer/component/init.lua
- lua/overseer/component/open_output.lua
- lua/overseer/strategy/init.lua
- lua/overseer/strategy/jobstart.lua
- lua/overseer/strategy/terminal.lua
- lua/overseer/task.lua
- lua/overseer/task_list/init.lua
- lua/overseer/task_list/sidebar.lua
- lua/overseer/task_view.lua
- lua/overseer/types.lua
- lua/overseer/window.lua
~~This new API is used internally by the floating preview window (when previewing a task in the list) and by the side-by-side preview window when overseer is opened in the bottom alignment (`:OverseerOpen bottom`).~~
Refactored to keep the new API internal, but add a `open_output` component that will open the task output under various conditions.
Incidentally fixes #298
> feat: new open_output component

- lua/overseer/template/task.lua
update `task` template to execute tasks in cwd of list tasks executed (for Taskfiles in child dirs)
> feat: fix template to set working dir for task

- lua/overseer/binding_util.lua
- lua/overseer/types.lua
The right hand side of bindings can be `false` to disable core bindings. This resolves that in the type definitions
> doc: fix docstring for `bidnings` where `rhs` can be `false`

- lua/overseer/template/vscode/init.lua
If you had a VSCode task which you wanted hidden from the tasks list, but this task depended on another, like the second task:
```json
{
"version": "2.0.0",
"tasks": [
{
"label": "Build",
"type": "shell",
"command": "gcc main.c",
"hide": true,
},
{
"label": "Callgrind",
"type": "shell",
"hide": true,
"command": "colorgrind",
"args": [
"--tool=callgrind",
"--callgrind-out-file=cg.out",
"./main"
],
"dependsOn": "Build"
},
{
"label": "Kcachegrind",
"type": "shell",
"command": "kcachegrind cg.out",
"dependsOn": "Callgrind",
}
]
}
```
only the "Build" task would be hidden, because of incorrect logic (which I actually introduced in b04b0b105c07b4f02b3073ea3a98d6eca90bf152, I'm sorry).
I moved the check to set the hide option in the template above the multiple "return" statement and tested it …
> fix: vscode task hide option was not set correctly

- lua/overseer/template/vscode/variables.lua
Added a whitelist for the VSCode task's variables which are unsupported by us. 
Now it warns only if variable is in whitelist.
I also moved the TODO comments closer to the whitelist.
> fix: don't warn on user defined vscode variables (#324)

- lua/overseer/strategy/toggleterm.lua
I found that https://github.com/stevearc/overseer.nvim/commit/1f5f271e00b82ced6a30ae5ad6dbe7d1104e5980 changed the toggleterm direction to `"float"` if users do not set them manually, reason not explained.
After a series of improvements for toggleterm be applied, this change is finally caused when starting a new task, the opening toggleterm will be `"float"`, even if the user prefers to keep it the default value of toggleterm.
For example, even if I prefer using a horizontal direction in toggleterm, and not setting the direction of toggleterm strategy in overseer, the terminal overseer opened will be `"float"`.
> fix: use the default toggleterm direction by default

- lua/overseer/strategy/toggleterm.lua
Using `fish` with `use_shell`  generate the following error:
```bash
fish: $? is not the exit status. In fish, please use $status.
```
This quick fix handle exit for fish, let me know if you prefer to add a function in `shell.lua`
> fix: exit for fish shell

- lua/cmp_overseer/init.lua
Relax the patterns that may trigger a cmp completion. \w was [a-zA-Z0-9_]. This didn't allow for "-" for instance. \S is everything but whitespace characters.
In my case I had strings containing `-` and the completion wouldn't work when I'd reach the `-` character.
> cmp completion: allow more patterns

- lua/overseer/form/utils.lua
the input may contain regex-special characters, for instance '%'. This function used to crash on strings containing '%'. Since we intended to do a substring comparison, just do that (otherwise we'd have to escape the regex characters in the string).
> form parse_value: more robust against input

- lua/overseer/template/cargo-make.lua
- lua/overseer/template/deno.lua
I found that some templates fail to execute if the configuration file is deeper than root because cwd is not set.
This PR fixes it for `deno` and `cargo-make` template. Other templates such as `composer` and `tox` seem to have the same problem, but I don't have those environments and couldn't test with them, so I didn't include them in this PR for now.
> fix: pass config file dir as cwd for cargo-make and deno template

- lua/overseer/template/npm.lua
- lua/overseer/template/vscode/provider/npm.lua
Bun will implement a text-based lockfile format in the future: [`bun.lock`](https://github.com/oven-sh/bun/issues/11863). This PR supports detecting `bun` as the command to use for running scripts defined in `package.json` by searching for `bun.lockb` and `bun.lock`, both of which will continue to be supported for a while.
> feat: support bun.lock

- lua/overseer/component/on_output_notify.lua
- lua/overseer/component/on_output_summarize.lua
- lua/overseer/util.lua
Adds a component that can be used as a replacement to `on_complete_notify`. `on_output_notify` will display a notification with task summary for long running tasks. This is helpful to get quick feedback without opening the overseer taskbar. This new component makes use of [nvim-notify](https://github.com/rcarriga/nvim-notify) to update the existing notification window, so when nvim-notify is not installed it will notify only when the task completes (and will display a one-time warning about nvim-notify).
To replace `on_complete_notify`:
```lua
require('overseer').setup {
component_aliases = {
default = {
{ "display_duration", detail_level = 2 },
"on_output_summarize",
"on_exit_set_status",
"on_output_notify", -- replaces on_complete_notify
{ "on_complete_dispose", require_view = { …
```
> feat: component to show real-time notification with output summary

- lua/overseer/task.lua
The problem doesn't always happen. I don't know what is the root cause.
Trying to move 'set local option' after 'set buffer to window'. It works.
> fix: number column randomly appears when opening output

- lua/overseer/task_bundle.lua
Currently, the `save_task_bundle` function does not delete the previous bundle if there are no tasks to save. This led to an issue where I expected no bundles to load on startup, and instead,  bundles from old sessions were loaded when the last session had no tasks to save.
This PR introduces a check to see if on_conflict is set to override (This made the most sense to me but but a new configuration option works too). If so, it calls delete_task_bundle when it detects that there are no tasks to save.
> Delete task bundle on save if no tasks and on_conflict=overwrite

- lua/overseer/util.lua
This PR attempt to fix #404 by adding the `silent = true` option to the `vim.fn.lcd()` call inside `utils.run_in_cwd()`.
> fix: silence cd output during utils.run_in_cwd().

- lua/overseer/component/on_result_diagnostics.lua
Fixes #429. 
This PR sets the diagnostic code on result diagnostic items sent by the `on_result_diagnostics` component. Please see #429 for details and for a minimal setup.
Note the error code `(arg-type)`.
> fix: set diagnostic code in on_result_diagnostics
