stevearc/overseer.nvim

lua/neotest/consumers/overseer.lua

Depends on https://github.com/nvim-neotest/neotest/pull/83
There is a bug with re-running Neotest "nearest test" runs. Those runs require fetching the current file name and line number of the cursor. If we naively try to pass the args to `neotest.run.run` again from a different buffer (because we've restarted the overseer task from a different buffer), the test discovery will fail.
The fix is to store the position_id along with the args, so that we can re-fetch the tree from the client and ensure we're running the same test, regardless of what buffer we're currently in.

fix: rerun neotest nearest from different buffer

---

lua/overseer/template/cargo.lua

Fixes #21. Let me know if any other changes need to be made!

feat(cargo): add run subcommand

---

.github/update_readme.py
README.md
doc/components.md
doc/explanation.md
doc/guides.md
doc/reference.md
doc/tutorials.md
lua/overseer/init.lua

Refactoring documentation to fit the [Diátaxis](https://diataxis.fr/) structure
Tasks remaining:

Refactor documentation

---

lua/overseer/template/builtin.lua
lua/overseer/template/deno.lua

Adds support for Deno's built-in task runner #77.

feat: support for deno's task runner

---

lua/overseer/template/builtin.lua
lua/overseer/template/rake.lua

introduce rake support

---

lua/overseer/template/builtin.lua
lua/overseer/template/task.lua

A task runner / simpler Make alternative written in Go
repo: https://github.com/go-task/task
homepage: https://taskfile.dev/

feat: support for taskfile

---

lua/overseer/template/builtin.lua
lua/overseer/template/composer.lua

Composer is the package manager for PHP.
https://getcomposer.org/

feat: add a composer template

---

lua/overseer/shell.lua
lua/overseer/strategy/toggleterm.lua
tests/shell_spec.lua

fix: correct shell escaping for toggleterm strategy

---

lua/overseer/template/vscode/problem_matcher.lua

Thanks for this cool plugin. What I was missing was a way to postprocess paths extracted from task output. This PR adds support for the `fileLocation` key as described in [tasks schema](https://code.visualstudio.com/docs/editor/tasks-appendix). Currently `params` is not passed to `replace_vars` so (from my understanding) things like `${input:x}` won't work. 
Example use case:
```json
"problemMatcher": {
"base": "$gcc",
"fileLocation": ["relative", "${workspaceFolder}/build"],
}
```

feat(vscode): support fileLocation in problemMatcher

---

lua/overseer/dap.lua

When using tasks with a problem matcher the task is started via `on_result()` callback which does not check task status, so even on error a new DAP session is started. This PR refactors the code a little bit to use the same callback in `on_complete/on_result` and always check the status. I assumed that only status that can be received in callbacks is SUCCESS/FAILURE, if others are possible then we'd probably need to tweak the logic.

fix: dap session is started even on task failure if task has a matcher

---

lua/overseer/template/builtin.lua
lua/overseer/template/cargo-make.lua

This PR adds basic support for [cargo-make](https://github.com/sagiegurari/cargo-make).

feat: Add support for cargo-make

---

lua/overseer/template/cargo.lua

Simple addition of the "clippy" command (linter / static analysis) to the cargo template.

feat: add support for cargo clippy

---

doc/tutorials.md

fix(docs): align tutorials.md with the current specs

---

doc/overseer.txt
doc/reference.md
lua/overseer/config.lua
lua/overseer/task_list/bindings.lua

feat: add close task list keybinding

---

lua/overseer/task_list/sidebar.lua

fix: save and restore sidebar window view

---

lua/overseer/template/just.lua

Remove restriction in justfile type

---

lua/overseer/template/npm.lua

fixes #242
Some projects have package.json files in subfolders, which are not the main project package.json file but rather some submodule marker. This seems prevalent in react-native projects. See this for instance: https://stackoverflow.com/questions/51701191/react-native-has-something-to-use-local-folders-as-package-name-what-is-it-ca To cover that case, we search for package.json files starting from the current file folder, up to the working directory, and pick the outermost candidate.

npm: smarter package.json file detection

---

lua/overseer/init.lua

The smallest patch you have ever seen :)

doc: correct `enable_dap` parameter to be optional

---

lua/overseer/shell.lua
tests/shell_spec.lua

fix: proper escaping for single quotes

---

lua/overseer/dap.lua

Don't continue debugging if preLaunchTask fails

---

doc/overseer.txt
doc/reference.md
lua/overseer/init.lua

Hi!
I believe that's a proper way to run `make all` with `OverseerRun`

Fix OverseerRun example

---

lua/overseer/template/vscode/init.lua

fix: error thrown in tasks.json does not contain tasks key
